#ifndef CONFIG_H
#define CONFIG_H

// Twitch credentials
#define TWITCH_OAUTH_TOKEN "YOUR_TWITCH_OAUTH_TOKEN"
#define TWITCH_NICK "YOUR_TWITCH_NICK"
#define TWITCH_CHANNEL "#YOUR_TWITCH_CHANNEL"

#endif // CONFIG_H
